### ISSUE TITLE
美股期权交易返回(-1, '不是可交易的证券类型')

### ISSUE THREAD

**Issue by peterfung** [FutunnOpen/py-futu-api#10]
trade_us_ctx.place_order(price=1.1, qty=1, code='US.AAPL190215P140000', trd_side=ft.TrdSide.BUY, order_type=ft.OrderType.NORMAL, trd_env=ft.TrdEnv.SIMULATE)
return (-1, '不是可交易的证券类型')

美股期权的code是US.AAPL190215P140000这样填写吗

FutuOpenD version 1.08
python futu api version 3.6.3

**Comment by FutunnOpen** [comment]
模拟交易暂时只支持正股

**Comment by peterfung** [comment]
改成TrdEnv.REAL还是一样
