### ISSUE TITLE
Error getting Stock Option price

### ISSUE THREAD

**Issue by beanyip** [FutunnOpen/py-futu-api#108]
quote_ctx.subscribe(['HK.HHImain','ALB220225P105000'], [SubType.ORDER_BOOK, SubType.QUOTE])

我开通了期权: LV1， 想用实时报价回调以上的指數和期权, 但程序停了沒能跑下去：

2021-11-30 11:04:45,144 | 7200 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=1, host=127.0.0.1, port=11111, user_id=17311346

**Comment by junmo1215** [comment]
> quote_ctx.subscribe(['HK.HHImain','ALB220225P105000'], [SubType.ORDER_BOOK, SubType.QUOTE])
> 
> 我开通了期权: LV1， 想用实时报价回调以上的指數和期权, 但程序停了沒能跑下去：
> 
> 2021-11-30 11:04:45,144 | 7200 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=1, host=127.0.0.1, port=11111, user_id=17311346

看上去ALB220225P105000这个代码没有带上市场，应该订阅会失败。在前面加上US.或者HK.
