### ISSUE TITLE
modify_user_security remove the stock from all groups by mistake

### ISSUE THREAD

**Issue by cyleefrank** [FutunnOpen/py-futu-api#110]
calling _quote_ctx.modify_user_security("A", ModifyUserSecurityOp.DEL, stock_list) will remove stock_list not just from group "A". It will remove stock_list from all other groups

**Comment by junmo1215** [comment]
> calling _quote_ctx.modify_user_security("A", ModifyUserSecurityOp.DEL, stock_list) will remove stock_list not just from group "A". It will remove stock_list from all other groups

ModifyUserSecurityOp.DEL would do this indeed.
if you don't want to DEL the stock from watchlist, you can use ModifyUserSecurityOp.MOVE_OUT
