### ISSUE TITLE
Unable to sort out daily max price %change in get_stock_filter

### ISSUE THREAD

**Issue by fhfung** [FutunnOpen/py-futu-api#118]
Hi, I would like to use get_stock_filter function call to sort out the stocks in daily max price pct change. When I use this code, it returns ok.
simple_filter = SimpleFilter()
simple_filter.filter_min = 5
simple_filter.filter_max = 500
simple_filter.stock_field = StockField.CHANGE_RATE_BEGIN_YEAR

However, when I change the stock_field to CHANGE_RATE. it returns "error:  不支持该过滤字段"
Please help me. Thanks.

**Comment by FutunnOpen** [comment]
> Hi, I would like to use get_stock_filter function call to sort out the stocks in daily max price pct change. When I use this code, it returns ok. simple_filter = SimpleFilter() simple_filter.filter_min = 5 simple_filter.filter_max = 500 simple_filter.stock_field = StockField.CHANGE_RATE_BEGIN_YEAR
> 
> However, when I change the stock_field to CHANGE_RATE. it returns "error: 不支持该过滤字段" Please help me. Thanks.

There 're several kind of Filter, but stock_field CHANGE_RATE only supported by AccumulateFilter, change SimpleFilter to AccumulateFilter will be OK
