### ISSUE TITLE
官方接口文档挂了？

### ISSUE THREAD

**Issue by longzhao1234** [FutunnOpen/py-futu-api#13]
官方接口文档404了。

**Comment by bowenli86** [comment]
靠 官方接口文档也能挂？这是说明这个project得有多不稳定   还有人敢用么？！

**Comment by FutunnOpen** [comment]
你好，在线文档目前正在维护，可在用户群共享中下载至本地查看，群号码为：229850364。

**Comment by longzhao1234** [comment]
自己备份了一下官方文档 防止文档被维护。
https://longzhao1234.github.io/futu-api-doc/
