### ISSUE TITLE
"No right to subscribe"

### ISSUE THREAD

**Issue by munum** [FutunnOpen/py-futu-api#130]
Hi I'm trying out the `quote_and_trade_demo.py` but it gives the error `* subscribe : (-1, 'No right to subscribe 00700')`. OpenD shows a subscription quota of 300.

Any advice appreciated.

**Comment by byblehua** [comment]
You must obtain the quotation permission first，please refer to here https://openapi.futunn.com/futu-api-doc/en/intro/authority.html#5331
OpenD shows a subscription quota of 300. It means after you had obtain permission before, you can subscription 300 types of data. Please refer to here https://openapi.futunn.com/futu-api-doc/en/intro/authority.html#9123
