### ISSUE TITLE
Authenticating multiple users using one running FutuOpenD gateway

### ISSUE THREAD

**Issue by indrarudianto** [FutunnOpen/py-futu-api#131]
Currently I'm developing a mobile app to track users portfolio using Futu API and py-futu-api. I have successfully logged in using FutuOpenD gateway on my Ubuntu Linux 22.04. As I understand and read from the API documentation (https://openapi.futunn.com/futu-api-doc/en/), the one running gateway only limited to one user. Is there any ways we can authenticate multiple users using one running gateway, e.g. in the cloud server? Currently I tested it out using Moomoo account. Thanks.

**Comment by byblehua** [comment]
Is there any ways we can authenticate multiple users using one running gateway, e.g. in the cloud server? 

This feature is not currently supported
