### ISSUE TITLE
unlock_trade failed:  ERROR. No one available account!

### ISSUE THREAD

**Issue by MrDannyWu** [FutunnOpen/py-futu-api#132]
unlock_trade failed:  ERROR. No one available account!

**Comment by MrDannyWu** [comment]
When I use the unlock interface, it prompts my account unlock_trade failed: ERROR. No one available account!
Please tell me how to operate to unlock successfully.

**Comment by muh005** [comment]
Hey @MrDannyWu, I asked their customer service, and got the following fix, probably this gonna fix your problem as well. 

https://github.com/FutunnOpen/py-futu-api/issues/133#issuecomment-1499860440

**Comment by MrDannyWu** [comment]
OK, thank you for your reply, I have also solved the customer service
inquiry, thank you again!
