### ISSUE TITLE
TradeDealHandlerBase callback not triggered

### ISSUE THREAD

**Issue by munum** [FutunnOpen/py-futu-api#135]
Hi I've noticed that, at least in simulation, callback for `TradeDealHandlerBase` isn't triggered even when the order is filled. `HandlerContext.recv_func` never receives value 2218 for `proto_id`. Is the callback supposed to function in simulation environment as well? The type for `rsp_pb` is either `Trd_SubAccPush_pb2.Response` or `Trd_UpdateOrder_pb2.Response`.

Thanks

**Comment by hughex** [comment]
https://openapi.futunn.com/futu-api-doc/en/qa/trade.html


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 下午4:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] TradeDealHandlerBase callback not triggered (Issue #135)





 
Hi I've noticed that, at least in simulation, callback for TradeDealHandlerBase isn't triggered even when the order is filled. HandlerContext.recv_func never receives value 2218 for proto_id. Is the callback supposed to function in simulation environment as well? The type for rsp_pb is always Trd_UpdateOrder_pb2.Response.
 
Thanks
