### ISSUE TITLE
官网找不到牛牛用户的futuopend的下载地址

### ISSUE THREAD

**Issue by dzygcc** [FutunnOpen/py-futu-api#137]
群也加满了，求一个FutuOpenD 的下载链接

**Comment by hughex** [comment]
请问需要什么系统的 FutuOpenD，可以通过邮件发给你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 下午2:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] 官网找不到牛牛用户的futuopend的下载地址 (Issue #137)





 
群也加满了，求一个FutuOpenD 的下载链接

**Comment by tsauliu** [comment]
求一个 FutuOpenD_7.0.3218_NN_Windows.7z 版本的，感恩
tsau.liu@gmail.com

**Comment by Olaful** [comment]
官网出公告了，目前下载不了

**Comment by edvardHua** [comment]
同求一个 FutuOpenD 的下载链接

**Comment by wzqkrl** [comment]
> 

求一个centOS版本的下载包，谢谢 wzq_krl@163.com

**Comment by MuGong8** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和Win 两个版本下载包，谢谢 (mailto:1603217168@qq.com)

**Comment by MuGong8** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和Win 两个版本下载包，谢谢 (mailto:1603217168@qq.com)

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和Win 两个版本下载包，谢谢 ([mailto:1603217168@qq.com](mailto:1603217168@qq.com))

已发送，请查收

**Comment by FutunnOpen** [comment]
> > 
> 
> 求一个centOS版本的下载包，谢谢 [wzq_krl@163.com](mailto:wzq_krl@163.com)

已发送，请查收

**Comment by LinFeng1997** [comment]
求一个 Mac 版的下载包，邮箱 ynublow@gmail.com @FutunnOpen

**Comment by troyzhao2023** [comment]
同求一个Mac版的下载包，邮箱 edfgt52res9x123okn@gmail.com @FutunnOpen 
感谢！

**Comment by FutunnOpen** [comment]
> [ynublow@gmail.com](mailto:ynublow@gmail.com)

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求一个 Mac 版的下载包，邮箱 [ynublow@gmail.com](mailto:ynublow@gmail.com) @FutunnOpen

已发送，请查收

**Comment by bestyuan** [comment]
求一个 win 版本的下载包，邮箱 caic50549@gmail.com 谢谢！ @FutunnOpen

**Comment by Esmidth** [comment]
求mac，windows和ubuntu版本的下载包，wzzjcp@gmail.com，谢谢 @FutunnOpen

**Comment by feilongbytedance** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和Mac两个版本下载包，2296685742@qq.com
@FutunnOpen

**Comment by pzh2386034** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 ubuntu和Mac两个版本下载包，(mailto:panzehua1@gmail.com)

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 ubuntu和Mac两个版本下载包，([mailto:panzehua1@gmail.com](mailto:panzehua1@gmail.com))
已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 ubuntu和Mac两个版本下载包，([mailto:panzehua1@gmail.com](mailto:panzehua1@gmail.com))

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和Mac两个版本下载包，[2296685742@qq.com](mailto:2296685742@qq.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 win版本下载包，邮箱 [312649062@qq.com](mailto:312649062@qq.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 win版本下载包，邮箱 [312649062@qq.com](mailto:312649062@qq.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求mac，windows和ubuntu版本的下载包，[wzzjcp@gmail.com](mailto:wzzjcp@gmail.com)，谢谢 @FutunnOpen

已发送，请查收

**Comment by pzh2386034** [comment]
请问要求手机验证码怎么办？
<img width="395" alt="image" src="https://github.com/FutunnOpen/py-futu-api/assets/9897310/969746aa-bb7a-49cd-ad06-0993755fe95c">

**Comment by FutunnOpen** [comment]
输入 'input_phone_verify_code -code = xxxxx'

**Comment by Garry1115** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和windows两个版本下载包，谢谢 , 邮箱：garry.zhang@foxmail.com
@FutunnOpen

**Comment by ch365** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和windows两个版本下载包，谢谢 , 邮箱：[365646846@qq.com](365646846@qq.com)
@FutunnOpen

**Comment by FutunnOpen** [comment]
> 已发送，请查收

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和windows两个版本下载包，谢谢 , 邮箱：[garry.zhang@foxmail.com](mailto:garry.zhang@foxmail.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和windows两个版本下载包，谢谢 , 邮箱：[365646846@qq.com](365646846@qq.com) @FutunnOpen

已发送，请查收

**Comment by ziofat** [comment]
麻烦发送一个windows版本的下载包，谢谢。printlts@gmail.com
@FutunnOpen

**Comment by nilikuai** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 ubuntu和Mac两个版本下载包，谢谢 , 邮箱：nilikuai@gmail.com

**Comment by ganquanemail** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[ganquanemail@gmail.com](mailto:zmountsky@gmail.com)
@FutunnOpen

**Comment by bpig** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac下载包，谢谢，邮箱 286287737@qq.com @FutunnOpen

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac下载包，谢谢，邮箱 [286287737@qq.com](mailto:286287737@qq.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[ganquanemail@gmail.com](mailto:zmountsky@gmail.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[zmountsky@gmail.com](mailto:zmountsky@gmail.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 ubuntu和Mac两个版本下载包，谢谢 , 邮箱：[nilikuai@gmail.com](mailto:nilikuai@gmail.com)

已发送，请查收

**Comment by ganquanemail** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 Windows 和Mac两个版本下载包，谢谢 , 邮箱：[47705046@qq.com](mailto:nilikuai@gmail.com)

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 Ubuntu、CentOS、Mac版本下载包，邮箱[oneraylee@163.com](mailto:oneraylee@163.com)。感激不尽！

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 Windows 和Mac两个版本下载包，谢谢 , 邮箱：[47705046@qq.com](mailto:nilikuai@gmail.com)

已发送，请查收

**Comment by ganquanemail** [comment]
换了2个邮箱，qq和gmail的都没有收到，您是哪个邮箱，163？我好换一下邮件地址。谢谢。 @FutunnOpen

**Comment by FutunnOpen** [comment]
> 47705046@qq.com

![image](https://github.com/FutunnOpen/py-futu-api/assets/25790136/f52a3de0-f1f3-4202-aa4c-d005dd8df6e5)
已再次发送，请查收

**Comment by mask-zpt** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：1074215802@qq.com
@FutunnOpen

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[1074215802@qq.com](mailto:1074215802@qq.com) @FutunnOpen

已发送，请查收

**Comment by ann2057** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac，windos和ubuntu三个版本下载包，谢谢 , 邮箱：1029212303@qq.com
@FutunnOpen

**Comment by sakuranew** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[1078885958@qq.com](mailto:1078885958@qq.com) @FutunnOpen

**Comment by bpig** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sakuranew ***@***.***&gt;
发送时间: 2023年8月23日 11:31
收件人: 286287737 ***@***.***&gt;
主题: Re: [FutunnOpen/py-futu-api] 官网找不到牛牛用户的futuopend的下载地址 (Issue #137)





 
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , ***@***.*** @FutunnOpen
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							Futu_OpenD_7.2.3408_Mac.tar.gz 							 (125.9MB, 2023年9月22日 14:33) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=c8990e3148552974faea4f31333239657751bf3631323965124919450750005001074c5005575d48045304541c060a000f4b5105030700070252535053532765711315446e7d490059223e061f0017560356596e7c535a4b4307131f56482dd6ec4fb2adad4c44c4707a46c0906b2e6b2f985c&key=c8990e3148552974faea4f31333239657751bf3631323965124919450750005001074c5005575d48045304541c060a000f4b5105030700070252535053532765711315446e7d490059223e061f0017560356596e7c535a4b4307131f56482dd6ec4fb2adad4c44c4707a46c0906b2e6b2f985c&code=7fa1129e&from=

**Comment by bpig** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 今月 ***@***.***&gt;
发送时间: 2023年8月22日 22:07
收件人: 286287737 ***@***.***&gt;
主题: Re: [FutunnOpen/py-futu-api] 官网找不到牛牛用户的futuopend的下载地址 (Issue #137)





 
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac，windos和ubuntu三个版本下载包，谢谢 , ***@***.***
 @FutunnOpen
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							Futu_OpenD_7.2.3408_Mac.tar.gz 							 (125.9MB, 2023年9月22日 14:33) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=c8990e3148552974faea4f31333239657751bf3631323965124919450750005001074c5005575d48045304541c060a000f4b5105030700070252535053532765711315446e7d490059223e061f0017560356596e7c535a4b4307131f56482dd6ec4fb2adad4c44c4707a46c0906b2e6b2f985c&key=c8990e3148552974faea4f31333239657751bf3631323965124919450750005001074c5005575d48045304541c060a000f4b5105030700070252535053532765711315446e7d490059223e061f0017560356596e7c535a4b4307131f56482dd6ec4fb2adad4c44c4707a46c0906b2e6b2f985c&code=7fa1129e&from=

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac，windos和ubuntu三个版本下载包，谢谢 , 邮箱：[1029212303@qq.com](mailto:1029212303@qq.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 已发送，请查收



> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[1078885958@qq.com](mailto:1078885958@qq.com) @FutunnOpen

已发送，请查收

**Comment by tuoyukun** [comment]
求mac和ubuntu两个系统的下载包，tuoyukun@gmail.com万分感谢。
@FutunnOpen

**Comment by tuoyukun** [comment]
求mac和ubuntu两个系统的下载包，tuoyukun@gmail.com万分感谢。
@FutunnOpen

**Comment by leksas** [comment]
求FutuOpenD 的 Ubuntu和windows两个版本下载包，谢谢 , 邮箱：[1329913700@qq.com]

**Comment by atrl** [comment]
528968@qq.com 求mac和ubuntu

**Comment by troyzhao2023** [comment]
感谢！求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS版本下载包，邮箱 edfgt52res9x123okn@gmail.com @FutunnOpen

PS: 抱歉之前只下载了Mac版，忘了下载CentOS版。结果开发完准备上服务器，发现过期了，只能重新求~~

**Comment by tuhulihongbing** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和windows两个版本下载包，谢谢 , 邮箱：[1285042680@qq.com]
@FutunnOpen

**Comment by FutunnOpen** [comment]
> 求mac和ubuntu两个系统的下载包，[tuoyukun@gmail.com](mailto:tuoyukun@gmail.com)万分感谢。 @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求FutuOpenD 的 Ubuntu和windows两个版本下载包，谢谢 , 邮箱：[[1329913700@qq.com](mailto:1329913700@qq.com)]

已发送，请查收

**Comment by FutunnOpen** [comment]
> [528968@qq.com](mailto:528968@qq.com) 求mac和ubuntu

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和windows两个版本下载包，谢谢 , 邮箱：[[1285042680@qq.com](mailto:1285042680@qq.com)] @FutunnOpen

已发送，请查收

**Comment by yutao404** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：14505775@qq.com
@FutunnOpen

**Comment by xjanker** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的Windows和[Ubuntu] 版本下载包  邮箱xjanker@gmail.com

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[14505775@qq.com](mailto:14505775@qq.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的Windows和[Ubuntu] 版本下载包 邮箱[xjanker@gmail.com](mailto:xjanker@gmail.com)

已发送，请查收

**Comment by 51fun** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的Windows和MAC 版本下载包 邮箱 lj_51fun@qq.com

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的Windows和MAC 版本下载包 邮箱 [lj_51fun@qq.com](mailto:lj_51fun@qq.com)

已发送，请查收

**Comment by treper** [comment]
求FutuOpenD 的 CentOS,windows,MacOS版本下载包，谢谢 , 邮箱 tanglek@qq.com

**Comment by HughChi** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：jhxtony@163.com

**Comment by a52682312** [comment]
为什么不放出来下载地址，而是用邮箱一个个发？

**Comment by fendouai** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[1722332572@qq.com](mailto:1722332572@qq.com)

**Comment by liuguangli** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢 , 邮箱：[244576106@qq.com](mailto:244576106@qq.com)
@FutunnOpen

**Comment by FutunnOpen** [comment]
> 求FutuOpenD 的 CentOS,windows,MacOS版本下载包，谢谢 , 邮箱 [tanglek@qq.com](mailto:tanglek@qq.com)

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[jhxtony@163.com](mailto:jhxtony@163.com)

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[1722332572@qq.com](mailto:1722332572@qq.com)

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢 , 邮箱：[244576106@qq.com](mailto:244576106@qq.com) @FutunnOpen

已发送，请查收

**Comment by cdredfox** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 CentOS,windows,MacOS下载包，谢谢 , 邮箱 cdredfox@gmail.com

**Comment by abc767234318** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 CentOS,windows,MacOS下载包，谢谢 , 邮箱 [2574549192@qq.com](2574549192@qq.com)

**Comment by h563k** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢 , 邮箱：[2277248178@qq.com](mailto:2277248178@qq.com)
@FutunnOpen

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 CentOS,windows,MacOS下载包，谢谢 , 邮箱 [cdredfox@gmail.com](mailto:cdredfox@gmail.com)

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢 , 邮箱：[2277248178@qq.com](mailto:2277248178@qq.com) @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢 , 邮箱：[2277248178@qq.com](mailto:2277248178@qq.com) @FutunnOpen

已发送，请查收

**Comment by rexchenkk** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢，邮箱：290603052@qq.com
@FutunnOpen

**Comment by Qsen1024** [comment]
麻烦给我发一下 win 和mac 的FutuOpenD ，邮箱 chengquansen@qq.com 谢谢 @FutunnOpen

**Comment by jiama2** [comment]
麻烦也发一下futuOpenD，包括mac和ubuntu版本，邮箱 twowon@qq.com   辛苦，谢谢@FutunnOpen

**Comment by JasonChen86899** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，邮箱是 [chenhao86899@gmail.com
](mailto:chenhao86899@gmail.com
)辛苦，谢谢@FutunnOpen

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，邮箱是 [chenhao86899@gmail.com ](mailto:chenhao86899@gmail.com)辛苦，谢谢@FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 已发送，请查收



> 麻烦也发一下mac，ubuntu和windows 3个版本的FutuOpenD，邮箱是 [twowon@qq.com](mailto:twowon@qq.com) 辛苦，谢谢@FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 麻烦给我发一下 win 和mac 的FutuOpenD ，邮箱 [chengquansen@qq.com](mailto:chengquansen@qq.com) 谢谢 @FutunnOpen

已发送，请查收

**Comment by FutunnOpen** [comment]
> 求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢，邮箱：[290603052@qq.com](mailto:290603052@qq.com) @FutunnOpen

已发送，请查收

**Comment by LCWdmlearning** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢，邮箱：[413645892@qq.com](mailto:413645892@qq.com) @FutunnOpen

**Comment by bpig** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac(Intel)版本下载包，谢谢，邮箱：286287737@qq.com  @FutunnOpen

**Comment by zhangshaopu** [comment]
麻烦也发一下mac，ubuntu和windows 3个版本的FutuOpenD，邮箱是 99432741@qq.com 辛苦，谢谢@FutunnOpen

**Comment by IZUMI-Zu** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac(Intel), Windows, ubuntu版本下载包，谢谢，邮箱：[274620705z@gmail.com](mailto:274620705z@gmail.com) @FutunnOpen

**Comment by FutunnOpen** [comment]
- OpenD-macOS: https://www.futunn.com/download/fetch-lasted-link?name=opend-macos
- OpenD-Ubuntu: https://www.futunn.com/download/fetch-lasted-link?name=opend-ubuntu
- OpenD-CentOS: https://www.futunn.com/download/fetch-lasted-link?name=opend-centos

**Comment by Jason-Jing** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢，邮箱：1647713328@qq.com @FutunnOpen

**Comment by Iongtimenosee** [comment]
OpenD-windows:https://www.futunn.com/download/fetch-lasted-link?name=opend-windows

**Comment by h563k** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、Windows 、Ubuntu 三个版本下载包，谢谢，邮箱：yf13755921935@gmail.com @FutunnOpen

**Comment by geodichen** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac、版本安装包，谢谢，邮箱地址geochen1202@gmail.com @FutunnOpen

**Comment by solarcult** [comment]
tian9527mr@sohu.com 求个Java版本的Win安装包和客户端

**Comment by IUgly** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac(m1), centos版本下载包，谢谢，邮箱：[crownjunlin@outlook.com] @FutunnOpen

**Comment by likeucode** [comment]
富途用户，求mac，windows和ubuntu版本的FutuOpenD下载包，liukeforget@163.com, 谢谢~

**Comment by Bobliew** [comment]
minghaoliao@qq.com 求一个FutuOpenD win和linux版本的下载包。

**Comment by aisjca** [comment]
mac m1 芯片的是不是用不了，安装了打开不了

**Comment by mrjiangyan** [comment]
求一个 mac与linux 的安装包，谢谢！邮箱 mrjiangyan@hotmail.com

**Comment by wanguolin** [comment]
可以发一个windows和linux的安装包吗：wanguolin@gmail.com
谢谢！

**Comment by spaceway007** [comment]
求windows版本的下载包,邮箱 y7giff7z@gmail.com,谢谢！

**Comment by kuangxi2017** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和Mac两个版本下载包，kuangchirs@gmail.com ,谢谢

**Comment by alfieliu** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Windows 、Ubuntu 2个版本下载包，谢谢，邮箱：253170568@qq.com @FutunnOpen

**Comment by terryzhang84730** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Windows Mac 版本 ，308035520@qq.com 谢谢！

**Comment by kavinsnow** [comment]
求一个 Mac 版的下载包，邮箱 64299985@qq.com   谢谢

**Comment by haogefeifei** [comment]
求一个 Mac 版的下载包，邮箱 [haogefeifei@qq.com](mailto:haogefeifei@qq.com) 谢谢....

**Comment by ZDLAY** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 CentOS和windows两个版本下载包，谢谢 , 邮箱：chinadlay@163.com @FutunnOpen

**Comment by MoreZero** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 Ubuntu和windows两个版本下载包，谢谢 , 邮箱：[570755030@qq.com] @FutunnOpen

**Comment by hzxhan2001** [comment]
求mac，windows和ubuntu版本的下载包，谢谢， 邮箱:65112167@qq.com
@FutunnOpen

**Comment by Wanguangji2023** [comment]
https://github.com/Wanguangji2023/Futu_openD_windows_zip

**Comment by snakepointid** [comment]
求centos7版本的下载包，谢谢， 邮箱:[snakefakeid@aliyun.com](mailto:snakefakeid@aliyun.com)
@FutunnOpen

**Comment by Fisher611** [comment]
求Windows版本的下载包，谢谢，邮箱： 978969231@qq.com
@FutunnOpen

**Comment by wudale** [comment]
求牛牛平台账号 (非moomoo) FutuOpenD 的 Mac与Windows 两个版本下载包，谢谢 , 邮箱：[wudale0577@gmail.com](mailto:wudale0577@gmail.com)
@FutunnOpen

**Comment by wudale** [comment]
OpenD-macOS: https://www.futunn.com/download/fetch-lasted-link?name=opend-macos
OpenD-Ubuntu: https://www.futunn.com/download/fetch-lasted-link?name=opend-ubuntu
OpenD-CentOS: https://www.futunn.com/download/fetch-lasted-link?name=opend-centos

**Comment by gaorufeng** [comment]
windows 版本 谢谢 sh18gao@gmail.com

**Comment by mfkxiaolei** [comment]
windows 和 mac 版本 谢谢 [mfkxiaolei@126.com](mailto:fkxiaolei@126.com)

**Comment by koala-ai** [comment]
求牛牛平台账号(非moomoo) FutuOpenD 的 MAC和windows两个版本下载包

**Comment by handlertang** [comment]
求一个windows安装包，谢谢 handlertang@hotmail.com

**Comment by hamlingong** [comment]
求一个mac版本的futuopend的安装包，谢谢：hamlingong@gmail.com

**Comment by Lazymanbj** [comment]
求一个 win11 版本的futu OpenD下载安装包，邮箱:lizm_bj@163.com, 谢谢！ @FutunnOpen

**Comment by byblehua** [comment]
> 求一个 win11 版本的futu OpenD下载安装包，邮箱:[lizm_bj@163.com](mailto:lizm_bj@163.com), 谢谢！ [@FutunnOpen](https://github.com/FutunnOpen)

windows   https://www.futunn.com/download/fetch-lasted-link?name=opend-windows
