### ISSUE TITLE
转了新版后，debug信息怎样停止显示？

### ISSUE THREAD

**Issue by kck1001** [FutunnOpen/py-futu-api#14]
转了新版后，debug信息怎样停止显示？

为什么以下的信息不停的显示？可否禁止？
[network_manager.py] do_send:283: Send: conn_id=1; proto_id=3001; serial_no=2583; total_len=66;
[network_manager.py] _on_packet:563: Recv: conn_id=1; proto_id=3011; serial_no=0; data_len=84; msg=;
[network_manager.py] _on_packet:563: Recv: conn_id=1; proto_id=3001; serial_no=2583; data_len=6; msg=;
[network_manager.py] _on_read:496: conn_id=1; elapsed=0.002033233642578125; recv_len=178; buf_len=178;

**Comment by FutunnOpen** [comment]
你好，如不需要显示debug信息，可以在FutuOpenD.xml文件中修改log_level为info或者更高的日志等级 即可停止debug信息的显示。
如仍有问题，可通过用户反馈群（号码：229850364）找管理员解决，谢谢。
