### ISSUE TITLE
请问Java的API包能从哪里下载？

### ISSUE THREAD

**Issue by solarcult** [FutunnOpen/py-futu-api#146]
最终从qq群文件下载到了.666

**Comment by IUgly** [comment]
你好，请问能发下opend的安装包吗？非常感谢～邮箱  @crownjunlin@outlook.com   @solarcult 

> 各位大佬，opend我有了最新的7.5.3708的版本，请问对应Java的API从哪里下载？ 发链接或者发到我邮箱里都行： [tian9527mr@sohu.com](mailto:tian9527mr@sohu.com) 谢谢。

**Comment by solarcult** [comment]
OpenD-macOS: https://www.futunn.com/download/fetch-lasted-link?name=opend-macos
OpenD-Ubuntu: https://www.futunn.com/download/fetch-lasted-link?name=opend-ubuntu
OpenD-CentOS: https://www.futunn.com/download/fetch-lasted-link?name=opend-centos
OpenD-windows: https://www.futunn.com/download/fetch-lasted-link?name=opend-windows

**Comment by solarcult** [comment]
最终千辛万苦通过了qq认证，从qq群文件下载到了.666
