### ISSUE TITLE
做的真烂！下单造成的损失要找谁负责？我要去APP上@你们老板！onPush_UpdateTicker 收到报价异常，TSLA和XLK报价低于实际价格10元以上，NVDA报价比实际价格高15块，用了一周多，发现出现了4次。难道没人用这个功能吗？还有这么严重的报价问题？真不靠谱！

### ISSUE THREAD

**Issue by solarcult** [FutunnOpen/py-futu-api#175]
XLK:
**XLK 美国时间：2024-06-26 11:04:06, XLK 实际价格是225.45，onPush_UpdateTicker 报价 213.39，相差竟然超过10块钱，造成程序下单卖出股票，做的真烂！我损失要找谁负责？**

以下是日志：
2024-06-26 10:56:29, XLK : I am in onPush_UpdateTicker, I am alive. Don't worry. :). now stockQty is : 17 , and now price is : 226.11
**2024-06-26 11:04:06, XLK NOW Hit Sell position hit price: 213.39**
2024-06-26 11:04:06, Calc Sell sellQty: 8
2024-06-26 11:04:06, Submit Sell order XLK, qty: 8, price: 212.75
2024-06-26 11:04:06, XLK Sad :( Sell order Not complete finished. FilledOrderQty: 0.0 and fillAvgPrice is: 0.0. now stockQty is : 17, waitingSell : 8
2024-06-26 11:04:07, XLK Sad :( Sell order Not complete finished. FilledOrderQty: 0.0 and fillAvgPrice is: 0.0. now stockQty is : 17, waitingSell : 8
2024-06-26 11:09:18, XLK Sad :( Sell order Not complete finished. FilledOrderQty: 0.0 and fillAvgPrice is: 0.0. now stockQty is : 17, waitingSell : 8
2024-06-26 11:09:19, XLK Happy :) Sell order finished filledOrderQty: 6.0 And FillAvgPrice is: 225.1416. now stockQty is : 11, waitingSell : 2
XLK mount is all right: 11
2024-06-26 11:09:31, XLK Sad :( Sell order Not complete finished. FilledOrderQty: 0.0 and fillAvgPrice is: 0.0. now stockQty is : 11, waitingSell : 2
2024-06-26 11:09:32, XLK Happy :) Sell order finished filledOrderQty: 12.0 And FillAvgPrice is: 225.0413. now stockQty is : -1, waitingSell : -10
XLK mount is all right: -1

![xlkerror](https://github.com/FutunnOpen/py-futu-api/assets/5895723/0ca77a14-6d04-47d0-9827-3c6e1380b7a2)

--

TSLA:
TSLA 美国时间 2024-06-26 11:59:27, TSLA 是价格是194.35 onPush_UpdateTicker 报价 178.5291，差的离谱。

2024-06-26 11:34:09, TSLA : I am in onPush_UpdateTicker, I am alive. Don't worry. :). now stockQty is : 53 , and now price is : 193.22
**2024-06-26 11:59:27, TSLA NOW Hit Sell position hit price: 178.5291**
2024-06-26 11:59:27, Calc Sell sellQty: 23
2024-06-26 11:59:27, Submit Sell order TSLA, qty: 23, price: 178.18

--

NVDA:
**NVDA美国时间2024-06-26 13:44:49, NVDA是价格是123.9 onPush_UpdateTicker 报价 139.0844，多了15块钱！**

2024-06-26 13:31:52, NVDA : I am in onPush_UpdateTicker, I am alive. Don't worry. :). now stockQty is : 26 , and now price is : 123.8
**2024-06-26 13:44:49, NVDA NOW Hit Buy position hit price: 139.0844**
2024-06-26 13:44:49, Calc buy status result: 3
2024-06-26 13:44:49, Calc Buy buyQty: 39
2024-06-26 13:44:49, Submit buy order NVDA, qty: 39, price: 139.37

**Comment by solarcult** [comment]
我就不明白了，时间点都给了，回看日志，查找到原因很难吗？难道这点技术水平和日志分析都没有？还说自己去对接美股数据源了？就这样吗? [叹气]

**Comment by byblehua** [comment]
你好，你的问题我们在查了

**Comment by lijian522904020** [comment]
您好，找相关同事排查了一下。这几个时间点确实都存在偏离市价较多的碎股逐笔成交的。我把相关的数据截图发给您。我们也在彭博机上做了二次比对，也是没问题的哈，截图我一并发出来。这些逐笔因为是碎股成交，所以K线上不会体现出来。纳斯达克逐笔还包含报告到finra nasdaq trf的场外成交，这种现象在美股正股是普遍存在的。抱歉github看得不是很及时，给您造成不好的体验了，下次遇到这类紧急问题，建议与我们的24小时客服联系，响应会更快一些。或者直接在微信群或者qq群反馈给我们的产品研发同事。
![20240627-124544](https://github.com/FutunnOpen/py-futu-api/assets/46236310/81ee996a-e8c4-4551-8af4-2517370d09fa)
![20240627-124550](https://github.com/FutunnOpen/py-futu-api/assets/46236310/93e11808-fdd2-4354-9560-82f196e9d830)
![20240627-124553](https://github.com/FutunnOpen/py-futu-api/assets/46236310/0b0db169-f14e-41be-8f91-13a06d8d83dd)
![20240627-124558](https://github.com/FutunnOpen/py-futu-api/assets/46236310/7433441b-08ad-4ce6-b87c-f1c72c7c3a19)
![20240627-124602](https://github.com/FutunnOpen/py-futu-api/assets/46236310/0afbf784-2699-437c-97ce-1cddcc4c9863)
![20240627-124606](https://github.com/FutunnOpen/py-futu-api/assets/46236310/d50ce3c0-0e84-417c-bd60-a408dc754834)
![20240627-124609](https://github.com/FutunnOpen/py-futu-api/assets/46236310/dce43907-5456-4631-9e84-1b55349dfd15)

**Comment by solarcult** [comment]
> 您好，找相关同事排查了一下。这几个时间点确实都存在偏离市价较多的碎股逐笔成交的。我把相关的数据截图发给您。我们也在彭博机上做了二次比对，也是没问题的哈，截图我一并发出来。这些逐笔因为是碎股成交，所以K线上不会体现出来。纳斯达克逐笔还包含报告到finra nasdaq trf的场外成交，这种现象在美股正股是普遍存在的。抱歉github看得不是很及时，给您造成不好的体验了，下次遇到这类紧急问题，建议与我们的24小时客服联系，响应会更快一些。或者直接在微信群或者qq群反馈给我们的产品研发同事。 ![20240627-124544](https://private-user-images.githubusercontent.com/46236310/343633770-81ee996a-e8c4-4551-8af4-2517370d09fa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY1NDYsIm5iZiI6MTcxOTQ2NjI0NiwicGF0aCI6Ii80NjIzNjMxMC8zNDM2MzM3NzAtODFlZTk5NmEtZThjNC00NTUxLThhZjQtMjUxNzM3MGQwOWZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NTgyN2QxZTJhZWQ4YTE2MTVlYzY0ZjhlNjhhYjUyMTkxOThhMzkzOGU0ZGFiYTNlOWViZmMwMDg3MTY1MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fQ-QJOUiNMTzOi71KuwIz2XjmV4x22GTdyXvGgbfIJ4) ![20240627-124550](https://private-user-images.githubusercontent.com/46236310/343633777-93e11808-fdd2-4354-9560-82f196e9d830.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY1NDYsIm5iZiI6MTcxOTQ2NjI0NiwicGF0aCI6Ii80NjIzNjMxMC8zNDM2MzM3NzctOTNlMTE4MDgtZmRkMi00MzU0LTk1NjAtODJmMTk2ZTlkODMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZjQ3YjE5MjIxY2Y5ZTg0MzJmZDNiOGE5MWVlODEwODJiMjZlZjZjZjE0ZWY0MTZlMWYyMTRiZTI0NTQ4ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98TEea4rhQ-I1aEv1PKeZPniW7-SqOPFbGWXEkFaBMM) ![20240627-124553](https://private-user-images.githubusercontent.com/46236310/343633780-0b0db169-f14e-41be-8f91-13a06d8d83dd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY1NDYsIm5iZiI6MTcxOTQ2NjI0NiwicGF0aCI6Ii80NjIzNjMxMC8zNDM2MzM3ODAtMGIwZGIxNjktZjE0ZS00MWJlLThmOTEtMTNhMDZkOGQ4M2RkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYmY5YTk1OTExNzFkZThmMmQ1NDFmZjgyOGY4ZDZmYzRlODVkYmYyMTdjODA4ZTg3NWE3MWM1Y2ZlNTFhZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0kZ1jG8MWMHypBPi5UGmE94jlo-V1liRfUuXUu6XH38) ![20240627-124558](https://private-user-images.githubusercontent.com/46236310/343633786-7433441b-08ad-4ce6-b87c-f1c72c7c3a19.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY1NDYsIm5iZiI6MTcxOTQ2NjI0NiwicGF0aCI6Ii80NjIzNjMxMC8zNDM2MzM3ODYtNzQzMzQ0MWItMDhhZC00Y2U2LWI4N2MtZjFjNzJjN2MzYTE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NTU4MTg4MjkzMjFhMjdjNzg3YWU2NThiMTljZWMzNDUzZGJjZWFmMTIzNjBlY2U1YzlkOWVkNTY5ZGNlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sohijTD48_QXbQpXD_t0vgtqzRcmqMhPu9utbIM0JiE) ![20240627-124602](https://private-user-images.githubusercontent.com/46236310/343633790-0afbf784-2699-437c-97ce-1cddcc4c9863.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY1NDYsIm5iZiI6MTcxOTQ2NjI0NiwicGF0aCI6Ii80NjIzNjMxMC8zNDM2MzM3OTAtMGFmYmY3ODQtMjY5OS00MzdjLTk3Y2UtMWNkZGNjNGM5ODYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMWUzMDJiZTBkYTdhMTM2M2Q3ZTc0NzQ1MjlhZjcyNjc1NTg5ZTY5OWM0ZjFmNDE4ZGQ4MmE2ZmRkNjNjYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPwsCGTumq_KuifydF2hkLTNiodo9y1xgSG6n1f3uhY) ![20240627-124606](https://private-user-images.githubusercontent.com/46236310/343633795-d50ce3c0-0e84-417c-bd60-a408dc754834.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY1NDYsIm5iZiI6MTcxOTQ2NjI0NiwicGF0aCI6Ii80NjIzNjMxMC8zNDM2MzM3OTUtZDUwY2UzYzAtMGU4NC00MTdjLWJkNjAtYTQwOGRjNzU0ODM0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZjQ5YWY4MzFmMWU0Njk2MDYzMWExNDQ1OGM5YmEwZmY1YWY1OWQzOTkzZjY0M2Q0ZDZiNzkxN2UxMzdiNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z0cLi6lKHkhqq-jKZcG1PWDaQx4dOdU6U2v6UEVs1uo) ![20240627-124609](https://private-user-images.githubusercontent.com/46236310/343633800-dce43907-5456-4631-9e84-1b55349dfd15.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY1NDYsIm5iZiI6MTcxOTQ2NjI0NiwicGF0aCI6Ii80NjIzNjMxMC8zNDM2MzM4MDAtZGNlNDM5MDctNTQ1Ni00NjMxLTllODQtMWI1NTM0OWRmZDE1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjY0MmIzNDM3OTUyYTJiMmQyOTUwN2U0YmY4YzllNjU0ZjA3OTc5OWE4ZTRlNTU5ZGUyNjkyYmIzZGMyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dThLct3RhiyeP-1GJnW8yFJWlDOJFDTivLEeIX8BOiE)

所以用你们这个ticker方案，一定会遇到这种上下跳跃不连贯的数据了？你们也不进行这种不连贯无意义数据的过滤？完全传给客户？

**Comment by solarcult** [comment]
懂了，就是别用这两个方案，用了就要自己处理异常情况，我建议在api里写清楚有可能出现波动交易数据，给使用者提个醒。还有这些：逐笔回调，分时回调，K线回调，摆盘回调，实时报价回调，每一分钟所产生的次数比例最好也能提供一下，我自己测过，ticker的数据会比rt的要多3倍，但这也不能每次都让用户自己对比啊。api上写清楚比较好，也显得专业点。你说呢？
