### ISSUE TITLE
Futu API seems unreliable

### ISSUE THREAD

**Issue by williswschan** [FutunnOpen/py-futu-api#178]
![PL Ratio](https://github.com/user-attachments/assets/772fa5ec-b9dc-4042-9ed9-10d7fa85c49a)

Kindly look at row #3 which is a opened position but pl_ratio is gone missing, I end up need to calculate it((cost_price - cur_price)/cost_price x 100) on my own...which is very unreliable. Anyone can explain why?

**Comment by potatobs4321** [comment]
> ![PL Ratio](https://private-user-images.githubusercontent.com/89602886/361126370-772fa5ec-b9dc-4042-9ed9-10d7fa85c49a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDA0MDksIm5iZiI6MTcyNDY0MDEwOSwicGF0aCI6Ii84OTYwMjg4Ni8zNjExMjYzNzAtNzcyZmE1ZWMtYjlkYy00MDQyLTllZDktMTBkN2ZhODVjNDlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyNDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZTE3Nzg3YjVkMTgwMzIxNzZjYjZlZDJlMTNmZDY4OTlkYTg3N2E4OTIxMDVkNTg4ZGNjYTA5YWIzYmJiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yWzzqKh6mDWxbINozsOZ3IXHWRUaFSxNB_TFhivG14Q)
> 
> Kindly look at row #3 which is a opened position but pl_ratio is gone missing, I end up need to calculate it((cost_price - cur_price)/cost_price x 100) on my own...which is very unreliable. Anyone can explain why?

You can try to set the parameter "refresh_cache" as True to get the latest statistics. Otherwise this function will return the data in OpenD's cache, which is refreshed by only about 3~5 minutes.
