### ISSUE TITLE
network_manager.py debug messages

### ISSUE THREAD

**Issue by kck1001** [FutunnOpen/py-futu-api#18]
你好，如不需要显示debug信息，可以在FutuOpenD.xml文件中修改log_level为info或者更高的日志等级 即可停止debug信息的显示。
如仍有问题，可通过用户反馈群（号码：229850364）找管理员解决，谢谢。

之前问的问题，试过行不通，在群已反馈，还没有答复。

**Comment by FutunnOpen** [comment]
set_futu_debug_model函数可以打开或关闭调试级别的log记录。
如果打开记录，则会记录info级别的log并且记录所有逐笔、摆盘、券商经纪的推送记录，以便于后面排查，文件记录在%appdata%(%HOME%)\com.futunn.FutuOpenD\Log下面
examples\analysis下面会有对逐笔、摆盘、券商经纪的推送记录的分析脚本，与我们联系，拿到原始交易所数据后，可以载入比对（beta功能）
