### ISSUE TITLE
Add pylint and flake8 autochecking

### ISSUE THREAD

**Issue by XVilka** [FutunnOpen/py-futu-api#19]
[Pylint](https://www.pylint.org/) and [flake8](http://flake8.pycqa.org/en/latest/) are famous Python code static analyzers. It would be awesome to add them into the building process.

It makes sense also to setup CI:
- [Travis CI](https://travis-ci.com/)
- [AppVeyor](https://www.appveyor.com/)
- or [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/)

So it would be possible to perform these kinds of checks automatically

**Comment by FutunnOpen** [comment]
你好，可加qq群108534288联系管理员解决。
