### ISSUE TITLE
如何配置文件证书登录

### ISSUE THREAD

**Issue by yufeiluo** [FutunnOpen/py-futu-api#20]
ssh免密码登录
1、客户端即A端生成RSA公钥和私钥
2、我们自己（A端）保留自己的私钥，然后把公钥id_rsa.pub存放到B端

富途的openapiD的登录配置方式有6种（富途intro文档  https://futunnopen.github.io/futu-api-doc/intro/FutuOpenDGuide.html#id7)

    1.命令行证书登录
    2.命令行帐号密码密文登录
    3.命令行帐号密码明文登录
    4.配置文件证书登录
    5.配置文件帐号密码密文登录
    6.配置文件帐号密码明文登录

第4中就是类同于ssh免密码登录吧，请问，公钥id_rsa.pub需要上传到富途的服务器上吗？如何传？

**Comment by FutunnOpen** [comment]
证书登录是不需要上传到富途的服务器，是在配置文件中填写证书路径即可。
目前不支持这种登录方式了哈~
