### ISSUE TITLE
在线获取复权因子（get_rehab）表中per_share_trans_ratio字段精度不足

### ISSUE THREAD

**Issue by guowenk** [FutunnOpen/py-futu-api#21]
用`get_rehab`在线获取复权因子表，表中如下字段精度不足：
* split_ratio   
* per_share_div_ratio    
* per_share_trans_ratio    
* allotment_ratio    
* stk_spo_ratio    

虽然数据类型是`float`，但是小数部分都是0，看起来像是`float(int(ratio))`，而且document中对此字段的解释是错误的，例如per_share_trans_ratio并不是每股转增股比例，并不是一个百分比，比如说SH.600489在2009-06-05每10股转增12股，这个ratio是用`10.0 / 12.0 = 0.8333`，如果是10股配3股，这个ratio是`10.0 / 3.0 = 3.3333`，通常这种类型的数据要保留四位小数，精度不够则无法使用。在futuquant版本中，`get_autype_list`得到的数据还是有很多位小数的。
烦请尽快检查下

**Comment by FutunnOpen** [comment]
收到，我们会尽快查的，感谢反馈。

**Comment by FutunnOpen** [comment]
![image](https://user-images.githubusercontent.com/25790136/76717036-5d24a400-676d-11ea-9b15-2cc351748446.png)
我们这边看到是保留超过4为小数的，请确认pandas打印的精度。
