### ISSUE TITLE
get_market_snapshot无法获取美股数据

### ISSUE THREAD

**Issue by lxywxh** [FutunnOpen/py-futu-api#25]
获取市场快照，股票代码设置成港股时可以正常返回，设置成美股时就无法正常返回。

代码如下：
from futu import *
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)
print(quote_ctx.get_market_snapshot('US.AAPL'))
quote_ctx.close()

报错：
(-1, 'NN_ProtoRet_TimeOut')

**Comment by triplewood** [comment]
同问。

**Comment by dominwong4** [comment]
推, 也太久沒修好了吧

**Comment by au-bzhang** [comment]
是不是一直就不行了。给个回复不行？

**Comment by FutunnOpen** [comment]
美股行情数据已下架，待与交易所沟通完数据转发权限后重新上线，排期未确定。

**Comment by darkice1** [comment]
2020 了还没好吗？

**Comment by PeopleComeAndGo** [comment]
额 app不是可以的吗？ 研究了半天，说美股行情数据下架了说 囧

**Comment by hughex** [comment]
尊敬的用户您好，富途于&nbsp;7&nbsp;月&nbsp;1&nbsp;日正式上线了仅适用于&nbsp;OpenAPI&nbsp;的美股&nbsp;Nasdaq&nbsp;Basic&nbsp;行情卡。您可以通过网页端的行情商城自行购买并激活，激活后须配合&nbsp;FutuOpenD&nbsp;2.14.1000&nbsp;以上的版本使用。行情卡购买链接点击：https://qtcard.futu5.com/buy?market_id=2&amp;channel=2


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 晚上9:09
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [FutunnOpen/py-futu-api] get_market_snapshot无法获取美股数据 (#25)





 
额 app不是可以的吗？ 研究了半天，说美股行情数据下架了说 囧

**Comment by fcce** [comment]
美股数据需要购买才能用，希望完善下文档
https://qtcard.futuhk.com/index/cards-mall?area_type=&is_peel_off=&lang=
