### ISSUE TITLE
自选股接口上限限制问题

### ISSUE THREAD

**Issue by llmyfa** [FutunnOpen/py-futu-api#26]
2.2.400的新增的自选股接口在新增自选分组股票后也会在默认的"全部"分组增加，删除对应分组股票时不会在"全部"里删除，系统也没有提供"全部"这个默认分组，导致很快达到自选股上限，无法再新增股票。

**Comment by FutunnOpen** [comment]
你好，我这边看是可以从"全部"分组中移除的，你可以加qq群108534288找管理员协助，谢谢。
