### ISSUE TITLE
k线订阅回调推送价格和成交量与按照时间段批量查询的数据不一致

### ISSUE THREAD

**Issue by lyswmp** [FutunnOpen/py-futu-api#29]

**Comment by lyswmp** [comment]
订阅 class CurKlineTest(CurKlineHandlerBase) k线，例如，恒指当月期货，K_1M，同一分钟推送多条，最后一条应该的数值 与 批量get_cur_kline拿到的数值不一致。抽样看了下get_cur_kline的结果是正确的，和客户端版本数据一样。

**Comment by loadatom** [comment]
已经修复，在测试中，测试通过就会发布。
