### ISSUE TITLE
行情权限不足 -1 

### ISSUE THREAD

**Issue by beautifulNow1992** [FutunnOpen/py-futu-api#3]
-1 行情权限不足

这个怎么开通权限？ 刚接触，想尝试量化 。获取行情就这个提示。 改怎么提高权限？

**Comment by FutunnOpen** [comment]
请具体描述哪个接口返回"行情权限不足"的问题。提示该错误可能是以下原因中的一个：

**Comment by FutunnOpen** [comment]
提示"行情权限不足"的原因可能是以下中的一个：
1、获取摆盘逐笔等需要港股Lv2权限；
2、获取A股委托明细需要A股Lv2权限；
如仍有疑问，请加QQ用户群联系管理员解决。谢谢。
