### ISSUE TITLE
为什么连接时总是提示超时？

### ISSUE THREAD

**Issue by Lanyd518** [FutunnOpen/py-futu-api#32]
![image](https://user-images.githubusercontent.com/26912888/68456118-efed8900-0237-11ea-8674-30d05894b694.png)

**Comment by Lanyd518** [comment]
难道是因为我把你们的服务器加入的防火墙黑名单？请问你们的服务器IP是什么？

**Comment by FutunnOpen** [comment]
请加qq群108534288找管理员协助解决，谢谢。

**Comment by kpbiao** [comment]
GUI 登录提示超时。  非 GUI 提示需要验证码，but 验证码在哪儿输入了？

**Comment by kpbiao** [comment]
qq 群已经加不了了。。  输入 11111 不对～
