### ISSUE TITLE
为什么拒绝我的连接?

### ISSUE THREAD

**Issue by BenCHANCH** [FutunnOpen/py-futu-api#33]
![image](https://user-images.githubusercontent.com/58131759/69491611-6c3bc980-0ed2-11ea-8d30-58821caa501a.png)

**Comment by FutunnOpen** [comment]
可能原因是：
1、你的连接数超过128了，请及时关闭不用的连接；
2、你本地未启动OpenD或者启动的OpenD监听端口不是11111。请先检查哦。
如还有问题，可加qq群108534288联系管理员解决，谢谢。
