### ISSUE TITLE
vnstation 2.1.1 接入富途后，无法订阅行情

### ISSUE THREAD

**Issue by MaoChen1980** [FutunnOpen/py-futu-api#38]
在vntrader gateway连接好之后，输入代码，回车

可以查询到 代码对应的名称

![fb](https://user-images.githubusercontent.com/5670446/77057636-35ed0180-6a0f-11ea-8728-feafc86e61a5.png)

futu log :
03-19 18:27:39(1584613659.580950) | 10420 | F3C | Info | Quote | SendSubReq By LasSubFailed
03-19 18:27:39(1584613659.580950) | 10420 | F3C | Info | Quote | SubQot 6211 Ret=1 UID=636726 AID=0 RK=3967188186676871702 SNO=16918 , enMktType = 2
03-19 18:27:39(1584613659.581963) | 10420 | F3C | Info | Quote | SubQot 6211 Ret=1 UID=636726 AID=0 RK=3967188186676871703 SNO=16919 , enMktType = 11
BlockingStatusThread 0 1584613662 class OMTcpServerImpl 9812
BlockingStatusThread 0 1584613662 class GTWWebSocket 10268
03-19 18:27:46(1584613666.629723) | 10420 | F3C | Info | Quote | OnReply_SubOrUnSub 6211 nReqKey=3967188186676871701 nSenderID=923682979 nSerialNo=16917 enProtoRet=-10000 nSvrRet=0 
..\..\..\Src\NNProtoCenter\Quote\NNBiz_Qot_PushQot.cpp 488 
03-19 18:27:46(1584613666.678607) | 10420 | F3C | Info | Quote | SendSubReq By LasSubFailed
03-19 18:27:46(1584613666.679602) | 10420 | F3C | Info | Quote | SubQot 6211 Ret=1 UID=636726 AID=0 RK=3967188186676871704 SNO=16920 , enMktType = 2

**Comment by FutunnOpen** [comment]
目前不支持美股行情数据。

**Comment by MaoChen1980** [comment]
不能订阅，也就是无法接受 tick， 无法用 futunn 的open api 交易美股了。 :(

**Comment by Sean-Wang** [comment]
请问什么时候可以开放美股的行情数据？
