### ISSUE TITLE
用Pyinstaller 打包后出现问题

### ISSUE THREAD

**Issue by samchan1123** [FutunnOpen/py-futu-api#39]
您好:
我在pycharm 载入了 futu library 后再打包成.exe
.exe 开启后未能如常运作，打开任务管理器后发现.exe 程序在不停自我复制。
即使仅仅加载library 而不使用亦出现此问题。
我的测试python code 如下:

from futu import *

if __name__ == "__main__":
    print('Hello')
    input()

但是用pycharm 运作完全正常。

**Comment by samchan1123** [comment]
我用以下方式打包:
pyinstaller -F ./[name].py

**Comment by haoqipaopao** [comment]
您好，第三方库的问题建议自查，我们无法提供这方面的指导
可以尝试把整个Python解释器环境一起拷走，应该可以成功打包exe运行。
> 我用以下方式打包：
> pyinstaller -F ./[name].py



> 您好：
> 我在pycharm加载了futu库后再打包成.exe
> .exe开启后替换如常运作，打开任务管理器后发现.exe程序在不停自我复制。
> 仅需加载库而不是使用亦出现此问题。
> 我的测试python代码如下：
> 
> 从futu进口*
> 
> 如果**name** ==“ **main** ”：
> print（'Hello'）
> input（）
> 
> 但是用pycharm运作完全正常。
