### ISSUE TITLE
RSA加密是不是有问题？

### ISSUE THREAD

**Issue by laradong** [FutunnOpen/py-futu-api#4]
按照说明操作，但是配上rsa_private_key连接就会异常。提示 
```
[network_manager.py] _on_packet:532: Recv: conn_id=1; proto_id=1001; serial_no=9429; data_len=128; msg=proto id:1001 conn_id:0 check sha error!;
```
即使用示例的RSA文件也不行，怀疑哪里有问题。

**Comment by wsj3000** [comment]
同感

**Comment by FutunnOpen** [comment]
使用rsa加密的步骤如下：
1、通过在线生成工具或者命令生成私钥，保存到本地；
2、在FutuOpenD.xml中配置参数rsa_private_key，需要填写绝对路径，如有OpenD运行过程中修改参数，需要重启OpenD；
3、在python代码中需要设置通讯协议加密，并设置本地的私钥绝对路径，具体接口参见：SysConfig.enable_proto_encrypt(True)；SysConfig.set_init_rsa_file("conn_key.txt")   # rsa 私钥文件路径
如有遇到问题，请按照以上步骤进行检查~如不能解决，请加入QQ用户反馈群找管理员解决。谢谢。
