### ISSUE TITLE
get_market_snapshot() 获取美股数据时超时!

### ISSUE THREAD

**Issue by manmadewind** [FutunnOpen/py-futu-api#43]
get_market_snapshot()接口获取美股数据时95%概率失败，少数股票才成功。
例如：quote_ctx.get_market_snapshot(['US.TSLA'])
得到返回：(-1, 'NN_ProtoRet_TimeOut')

获取A股和港股正常。

**Comment by a14843** [comment]
I also see the same NN_ProtoRet_TimeOut issue. Should I try increasing the timeout? 
Version used: 3.21 (pip install py-futu-api)

**Comment by Vankeee** [comment]
解决了吗？

**Comment by hughex** [comment]
尊敬的用户您好，富途于&nbsp;7&nbsp;月&nbsp;1&nbsp;日正式上线了仅适用于&nbsp;OpenAPI&nbsp;的美股&nbsp;Nasdaq&nbsp;Basic&nbsp;行情卡。您可以通过网页端的行情商城自行购买并激活，激活后须配合&nbsp;FutuOpenD&nbsp;2.14.1000&nbsp;以上的版本使用。行情卡购买链接点击：https://qtcard.futu5.com/buy?market_id=2&amp;channel=2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"acwchang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 下午3:04
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [FutunnOpen/py-futu-api] get_market_snapshot() 获取美股数据时超时! (#43)





 
解决了吗？

**Comment by PeopleComeAndGo** [comment]
@hughex 是不是买lv1 全美综合报价这个，就可以获得美股实时行情数据了？

**Comment by hughex** [comment]
尊敬的用户您好，富途于&nbsp;7&nbsp;月&nbsp;1&nbsp;日正式上线了仅适用于&nbsp;OpenAPI&nbsp;的美股&nbsp;Nasdaq&nbsp;Basic&nbsp;行情卡。您可以通过网页端的行情商城自行购买并激活，激活后须配合&nbsp;FutuOpenD&nbsp;2.14.1000&nbsp;以上的版本使用。行情卡购买链接点击：https://qtcard.futu5.com/buy?market_id=2&amp;channel=2
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 晚上11:02
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"休"<384862429@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FutunnOpen/py-futu-api] get_market_snapshot() 获取美股数据时超时! (#43)





 
@hughex 是不是买lv1 全美综合报价这个，就可以获得美股实时行情数据了？

**Comment by FutunnOpen** [comment]
https://qtcard.futu5.com/buy?market_id=2&amp;channel=2行情卡就可以获取到美股实时行情数据。
