### ISSUE TITLE
Incorrect Time format - mili-second missing leading zeros

### ISSUE THREAD

**Issue by jackhftang** [FutunnOpen/py-futu-api#47]
In the returning data of `OrderBookHandlerBase`.`on_recv_rsp`, for example
```
{'code': 'HK.MHI2005', 'svr_recv_time_bid': '2020-05-07 15:07:42.8', 'svr_recv_time_ask': '2020-05-07 15:07:42.8', 'Bid': [...], 'Ask': [...]}
```
I receive time string of `svr_recv_time_bid` and `svr_recv_time_ask` like the following
2020-05-07 15:07:42
2020-05-07 15:07:42.8
2020-05-07 15:07:42.88
2020-05-07 15:07:42.888

Originally, I thought that `2020-05-07 15:07:42.8` means `2020-05-07 15:07:42.800`. However, when I collected data later. I found statistically there are no timestamp that mili-second is starting with 0, i.e. format like `yyyy-MM-dd hh:mm:ss.0zz` or `yyyy-MM-dd hh:mm:ss.00z`. 

So I infer that `2020-05-07 15:07:42.8` actually means `2020-05-07 15:07:42.008`. This is not a conventional format of time! And should be considered as a bug.

**Comment by FutunnOpen** [comment]
收到，我们尽快处理，感谢反馈。

**Comment by jackhftang** [comment]
Is it going to be fixed? why close this issue?

**Comment by FutunnOpen** [comment]
已经修复了，大概会在10月份发布。
