### ISSUE TITLE
咨询行情协议 3001 与 3002 的区别和设计

### ISSUE THREAD

**Issue by liyuntao** [FutunnOpen/py-futu-api#51]
Qot_Sub.proto - 3001订阅或者反订阅
Qot_RegQotPush.proto - 3002注册行情推送

这两个协议看起来十分相似，似乎订阅后的 security 还需要再注册推送后才可以获得推送。
请问将 3001 3002 区分设计的考量是什么？可否合并成一个？

**Comment by hughex** [comment]
3001订阅已经包含注册行情推送的功能，
3001 3002 区分设计的考量是用于一条连接用于同步，另外一条用户接收异步请求的场景。
如果一条连接用于订阅，并在该条连接上接收推送，只使用3001协议即可。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"acwchang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 晚上7:59
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] 咨询行情协议 3001 与 3002 的区别和设计 (#51)





 
Qot_Sub.proto - 3001订阅或者反订阅
 Qot_RegQotPush.proto - 3002注册行情推送
 
这两个协议看起来十分相似，似乎订阅后的 security 还需要再注册推送后才可以获得推送。
 请问将 3001 3002 区分设计的考量是什么？可否合并成一个？

**Comment by liyuntao** [comment]
Hi @hughex   感谢您的解答

关于 
> 一条连接用于同步，另外一条用户接收异步请求的场景
这个场景这里我还有一些疑惑，这里 `同步`与 `接收异步请求` 是在客户端视角下看待的么？
还是说，将行情数据包与其他比如指令相关的命令包，分开了不同的通道进行传输？

**Comment by hughex** [comment]
同步与接收异步请求是在客户端视角下看待的。
客户端可以选择创建多条连接，在不同连接上面选择只发送接收请求或只接收推送。
如果有更多问题，建议加入QQ群108534288联系群管理。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"acwchang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 晚上8:35
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"休"<384862429@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FutunnOpen/py-futu-api] 咨询行情协议 3001 与 3002 的区别和设计 (#51)





 
Hi @hughex   感谢您的解答
 
关于
  
一条连接用于同步，另外一条用户接收异步请求的场景
 这个场景这里我还有一些疑惑，这里 同步与 接收异步请求 是在客户端视角下看待的么？
 还是说，将行情数据包与其他比如指令相关的命令包，分开了不同的通道进行传输？

**Comment by liyuntao** [comment]
十分感谢~
