### ISSUE TITLE
Still, not support US?

### ISSUE THREAD

**Issue by dominwong4** [FutunnOpen/py-futu-api#53]
print(quote_ctx.get_market_snapshot('US.AAPL'))
(-1, 'NN_ProtoRet_TimeOut')

**Comment by hughex** [comment]
富途于&nbsp;7&nbsp;月&nbsp;1&nbsp;日正式上线了仅适用于&nbsp;OpenAPI&nbsp;的美股&nbsp;Nasdaq&nbsp;Basic&nbsp;行情卡。您可以通过网页端的行情商城自行购买并激活，激活后须配合&nbsp;FutuOpenD&nbsp;2.14.1000&nbsp;以上的版本使用。行情卡购买链接点击：https://qtcard.futu5.com/buy?market_id=2&amp;channel=2
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 凌晨0:36
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] Still, not support US? (#53)





 
print(quote_ctx.get_market_snapshot('US.AAPL'))
 (-1, 'NN_ProtoRet_TimeOut')
