### ISSUE TITLE
想知道目前富途对于用户调用接口次数的限制是什么样的？

### ISSUE THREAD

**Issue by weiguang-zz** [FutunnOpen/py-futu-api#54]

**Comment by hughex** [comment]
请参考文档
https://futunnopen.github.io/futu-api-doc/protocol/intro.html#quota-limit




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 上午9:32
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] 想知道目前富途对于用户调用接口次数的限制是什么样的？ (#54)
