### ISSUE TITLE
涨跌停价格，最小变动价位，断线自动撤单功能

### ISSUE THREAD

**Issue by lianyidao** [FutunnOpen/py-futu-api#56]
可否在后续版本提供股票涨跌停价格，最小变动价位等数据

可否在后续版本提供报单请求字段‘cancel_on_disconnect: bool'，如果为True，则当客户端断线时，服务器自动撤销该笔报单

**Comment by FutunnOpen** [comment]
1、最小变动价位等数据，在get_market_snapshot接口中查看。
2、已记录需求。
