### ISSUE TITLE
港股ipo 历史中签数据

### ISSUE THREAD

**Issue by tcloaa** [FutunnOpen/py-futu-api#57]
非常喜欢这个py api

想问一下目前支持抓取历史ipo中签数据吗？比如每一手有多少人申购，然后有多少人中签之类的（就像手机app页面展示的数据）。谢谢

**Comment by hughex** [comment]
看下这个接口是否满足需求
https://futunnopen.github.io/futu-api-doc/api/Quote_API.html#get-ipo-list


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 晚上11:45
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] 港股ipo 历史中签数据 (#57)





 
非常喜欢这个py api
 
想问一下目前支持抓取历史ipo中签数据吗？比如每一手有多少人申购，然后有多少人中签之类的（就像手机app页面展示的数据）。谢谢
