### ISSUE TITLE
例子中的小bug

### ISSUE THREAD

**Issue by shaoyucheng** [FutunnOpen/py-futu-api#60]
文件路径：[futu/examples/macd_strategy.py](url)

代码段
`cash = acc_info['Power'][0]  # 购买力`

Power首字母应为小写即：

`cash = acc_info['power'][0]  # 购买力`

否则将会报如下错误：
![image](https://user-images.githubusercontent.com/8242211/93552222-846d5f80-f9a2-11ea-884a-8ab105c16d6e.png)

**Comment by hughex** [comment]
谢谢，会在3.26上修改。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 中午11:32
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] 例子中的小bug (#60)





 
文件路径：futu/examples/macd_strategy.py
 
代码段
 cash = acc_info['Power'][0]  # 购买力
 
Power首字母应为小写即：
 
cash = acc_info['power'][0]  # 购买力
 
否则将会报如下错误：
