### ISSUE TITLE
發行訊息

### ISSUE THREAD

**Issue by kitkimwong** [FutunnOpen/py-futu-api#62]
您好，非常喜歡這個API
請問API能拿到發行資料嗎？
比如下圖的基石投資者，我看get_ipo_list沒有這些數據
![image](https://user-images.githubusercontent.com/11818108/93752973-032bfc00-fc32-11ea-90e5-31df764971e9.png)

**Comment by kitkimwong** [comment]
@FutunnOpen

**Comment by FutunnOpen** [comment]
你好，感谢反馈，已记录需求。
