### ISSUE TITLE
按日期查询复权数据

### ISSUE THREAD

**Issue by lianyidao** [FutunnOpen/py-futu-api#63]
当前get_rehab接口只能查询单只股票的数据，要更新最新的复权数据必须逐个代码查询耗时比较久。
是否能够在get_rehab接口增加'trade_date'参数，
比如code='', trade_date='20200925'，返回ex_div_date==20200925这一天的复权数据，
一天的复权数据量应该挺少的，不会给服务器造成太大的压力。

**Comment by FutunnOpen** [comment]
你好，感谢你的建议，已记录需求。
