### ISSUE TITLE
Use context manger to close the connection when finished

### ISSUE THREAD

**Issue by damonYuan** [FutunnOpen/py-futu-api#64]
创建 context manger 来关闭连接。

**Comment by FutunnOpen** [comment]
你好，你可以使用SysConfig.set_all_thread_daemon(True)接口设置内部创建的线程都是daemon。这样会自动关闭连接。
具体使用方法可以参考：https://openapi.futunn.com/futu-api-doc/ftapi/init.html#4570

如还有其他问题，请加qq群229850364联系管理员协助。
