### ISSUE TITLE
有计划支持美股吗？

### ISSUE THREAD

**Issue by aoxn** [FutunnOpen/py-futu-api#67]

**Comment by FutunnOpen** [comment]
富途于 7 月 1 日正式上线了仅适用于 OpenAPI 的美股 Nasdaq Basic 行情卡。您可以通过网页端的行情商城自行购买并激活，激活后须配合 FutuOpenD 2.14.1000 以上的版本使用。行情卡购买链接点击：https://qtcard.futuhk.com/buy?market_id=2&good_type=12&channel=2#/
有其他问题可以加qq群229850364找管理员协助。
