### ISSUE TITLE
return wrong <HSI index option price> by <get_order_book> 

### ISSUE THREAD

**Issue by zebrapen** [FutunnOpen/py-futu-api#68]
-the <get_order_book> can get the option price, but some of it is wrong!
-option prices of some strikes are having the wrong bid+ask price. The bid+ask price is not changed for the whole morning or afternoon.
-option price of some strikes are correct. 
-please fix the issue and follow!

**Comment by FutunnOpen** [comment]
Which HSI index option ? Does it appear often？
Please provide more  information.
Please contact Futu OpenAPI developers via QQ(108534288)/WeChat to facilitate instant communication and file transferation.

**Comment by zebrapen** [comment]
I would say this happening very often, it is happening now(2020-12-10 15:00)
the HK.HSI201230P24800, is not having the right bid price. The return value is 59, but what I see in other platform is 48.

**Comment by FutunnOpen** [comment]
other platform means ?
the HK.HSI201230P24800,  the bid price in Futu Windows Client is 59
![image](https://user-images.githubusercontent.com/25790136/101733133-5149f080-3af9-11eb-9371-9be9c4cfb454.png)

**Comment by zebrapen** [comment]
![Capture](https://user-images.githubusercontent.com/75713997/101733362-b1409700-3af9-11eb-9e0f-8d7bd5ad07a7.JPG)

**Comment by FutunnOpen** [comment]
感谢反馈，我们跟行情后台确认一下。

**Comment by zebrapen** [comment]
please take this seriously, it is an a critical issue....

**Comment by FutunnOpen** [comment]
后台已修复并发布
