### ISSUE TITLE
条件选股返回字段缺失

### ISSUE THREAD

**Issue by Damocs0921** [FutunnOpen/py-futu-api#70]
def getFilteredStockData(market,plate_code,stock_field):
	simple_filter = SimpleFilter()
	simple_filter.stock_field = StockField.NET_PROFIT
	simple_filter.sort = SortDir.DESCEND
	# simple_filter.is_no_filter = False;
	# simple_filter.filter_min = 0
	# financial_filter.filter_max = 1000
	ret, ls = quote_ctx.get_stock_filter(Market.HK, [simple_filter],plate_code)  # 对香港市场的股票做简单筛选
	if ret == RET_OK:
	    last_page, all_count, ret_list = ls
	    # print(len(ret_list), all_count, ret_list)
	    print(ret_list);
	else:
	    print('error: ', ls)

返回[ stock_code:HK.08451  stock_name:日光控股 ,  stock_code:HK.03332  stock_name:中生联合 ,  stock_code:HK.01259  stock_name:未来发展控股 ,  stock_code:HK.01112  stock_name:H&H国际控股 ,  stock_code:HK.01338  stock_name:霸王集团 ,  stock_code:HK.03828  stock_name:明辉国际 ,  stock_code:HK.03331  stock_name:维达国际 ,  stock_code:HK.00653  stock_name:卓悦控股 ,  stock_code:HK.08163  stock_name:领智金融 ,  stock_code:HK.00399  stock_name:领航医药生物科技 ,  stock_code:HK.01173  stock_name:威高国际 ,  stock_code:HK.01044  stock_name:恒安国际 ,  stock_code:HK.08281  stock_name:中国金典集团 ]

只有代码和股票名，没有https://openapi.futunn.com/futu-api-doc/quote/get-stock-filter.html
文档中所述stock_list包含的其它参数（市盈率，资产周转率等），是什么原因呢？

我是否需要再购买某种权限包？

**Comment by haoqipaopao** [comment]
你好，建议添加一下我们的官方QQ群108534288，在群里咨询问题可以得到及时回复哈。
1.  simple_filter.is_no_filter = False;这句需要，不能注释掉。
2.  simple_filter = SimpleFilter()与simple_filter.stock_field = StockField.NET_PROFIT不是同一类型属性。可以修改simple_filter =FinancialFilter() 因为NET_PROFIT属于财务属性。
![image](https://user-images.githubusercontent.com/16208127/119597405-85993b00-be13-11eb-8967-89609a8b6cd3.png)
