### ISSUE TITLE
AttributeError: 'OpenQuoteContext' object has no attribute 'get_autype_list'

### ISSUE THREAD

**Issue by wr72000** [FutunnOpen/py-futu-api#71]
Traceback (most recent call last):
  File "Atesting.py", line 16, in <module>
    print(quote_ctx.get_autype_list(code_list))
AttributeError: 'OpenQuoteContext' object has no attribute 'get_autype_list'

**Comment by FutunnOpen** [comment]
你好，该接口已经不再维护了，如需获取复权数据，可使用如下接口：
https://openapi.futunn.com/futu-api-doc/quote/get-rehab.html

如后续还有问题，请加qq群229850364联系管理员协助。
