### ISSUE TITLE
不能打包成exe

### ISSUE THREAD

**Issue by xuhanlin1** [FutunnOpen/py-futu-api#72]
为什么用了futu的程序无法打包 求解

**Comment by xuhanlin1** [comment]
报错是 运行exe时，cmd报错找不到 Common_pb2 模块

**Comment by FutunnOpen** [comment]
你好，请尝试用以下方法解决：
   pyinstaller script.py
   执行完了默认放到dist目录，然后
   futu/common/pb下的py复制到dist根目录
   futu/VERSION.txt复制到dist/futu目录

如还未解决，请加qq群229850364联系管理员协助。
