### ISSUE TITLE
请求的历史K线数据不一致

### ISSUE THREAD

**Issue by JustLuoyu** [FutunnOpen/py-futu-api#75]
同样的request, 但是拿到的股票数据竟然会不一样. 
比如 00700, 2021-1-20 9:30的1min KL:
{"time":"2021-01-20 09:30:00","isBlank":false,"highPrice":671,"openPrice":671,"lowPrice":671,"closePrice":671,"lastClosePrice":655,"volume":1568100,"turnover":1052195100,"turnoverRate":0,"pe":0,"changeRate":2.4427480916030535,"timestamp":1611106200}
{"time":"2021-01-20 09:30:00","isBlank":false,"highPrice":671,"openPrice":671,"lowPrice":671,"closePrice":671,"lastClosePrice":655,"volume":1568100,"turnover":1052195100,"turnoverRate":0,"pe":0,"changeRate":0,"timestamp":1611106200}
上面是两次请求拿到的1min KL数据. changeRate会变成0. 
测试过多只股票, 只要重复请求3次以上就一定会出现changeRate改变.
这个问题很大, 要慌.

**Comment by FutunnOpen** [comment]
你好，问题已收到，已反馈给相关研发同学处理。如后续还有问题，请加qq群229850364联系管理员协助。

**Comment by FutunnOpen** [comment]
该问题预计在6月上旬发布的包中修复
