### ISSUE TITLE
api能支持股票指标么，如EMA， KDJ等

### ISSUE THREAD

**Issue by zhanghaocol** [FutunnOpen/py-futu-api#76]
api能支持股票指标么，如EMA， KDJ等

**Comment by hughex** [comment]
api不支持指标接口。
可以通过api获取K线数据，再通过自编或第三方指标算法计算。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 中午11:48
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] api能支持股票指标么，如EMA， KDJ等 (#76)





 
api能支持股票指标么，如EMA， KDJ等

**Comment by JonasLLLLL** [comment]
安裝了TA-Lib, 請問如何用api的k線數據去計算技術指標? Thanks.
