### ISSUE TITLE
A股交易OpenTradeContext函数

### ISSUE THREAD

**Issue by tcloaa** [FutunnOpen/py-futu-api#78]
你好，

官方文档上只提供了港股交易函数api `OpenHKTradeContext`，我自己尝试后也试出了美股`OpenUSTradeContext`。

请问在哪里可以找到A股通、期货、新加坡的对应函数借口？

**Comment by hughex** [comment]
A股通&nbsp;OpenHKCCTradeContext
期货&nbsp;OpenFutureTradeContext
新加坡暂不支持，详情见以下链接
https://openapi.futunn.com/futu-api-doc/trade/base.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月20日(星期六) 晚上7:34
收件人:&nbsp;"FutunnOpen/py-futu-api"<py-futu-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] A股交易OpenTradeContext函数 (#78)





 
你好，
 
官方文档上只提供了港股交易函数api OpenHKTradeContext，我自己尝试后也试出了美股OpenUSTradeContext。
 
请问在哪里可以找到A股通、期货、新加坡的对应函数借口？
