### ISSUE TITLE
美股 get_cur_kline 拿不到數據

### ISSUE THREAD

**Issue by tlchan5** [FutunnOpen/py-futu-api#8]
你好, 我用get_cur_kline()拿不到美股數據,只回傳了一個空的dataframe 也沒有error message
![image](https://user-images.githubusercontent.com/25591449/50981502-0f435900-1536-11e9-8cb9-dd5661b2c8bd.png)

我查詢港股的話就沒問題
![image](https://user-images.githubusercontent.com/25591449/50981605-52053100-1536-11e9-9c45-fde18e50ad22.png)

**Comment by FutunnOpen** [comment]
QQ群已发公告, 美股定阅暂时下架
