### ISSUE TITLE
港股期权get_market_snapshot 返回NN_ProtoRet_TimeOut, error -1

### ISSUE THREAD

**Issue by hugoleung1225** [FutunnOpen/py-futu-api#82]
港股也不能了??

**Comment by fhfung** [comment]
Error: NN_ProtoRet_TimeOut

**Comment by fhfung** [comment]
港股get_market_snapshot功能是否不再支持？

**Comment by hughex** [comment]
后台服务问题，麻烦提供一下牛牛号




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 上午10:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [FutunnOpen/py-futu-api] 港股期权get_market_snapshot 返回NN_ProtoRet_TimeOut, error -1 (#82)





 
港股get_market_snapshot功能是否不再支持？

**Comment by hughex** [comment]
后台服务问题，麻烦提供一下牛牛号




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 上午10:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [FutunnOpen/py-futu-api] 港股期权get_market_snapshot 返回NN_ProtoRet_TimeOut, error -1 (#82)





 
Error: NN_ProtoRet_TimeOut

**Comment by hughex** [comment]
后台服务问题，麻烦提供一下牛牛号




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 凌晨2:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] 港股期权get_market_snapshot 返回NN_ProtoRet_TimeOut, error -1 (#82)





 
港股也不能了??

**Comment by fhfung** [comment]
12358912

> 后台服务问题，麻烦提供一下牛牛号
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FutunnOpen/py-futu-api" ***@***.***&gt;; 发送时间:&nbsp;2021年3月25日(星期四) 凌晨2:20 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[FutunnOpen/py-futu-api] 港股期权get_market_snapshot 返回NN_ProtoRet_TimeOut, error -1 (#82) 港股也不能了?? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hughex** [comment]
@fhfung 请重启FutuOpenD验证下是否修复

**Comment by fhfung** [comment]
可以了，感激

> @fhfung 请重启FutuOpenD验证下是否修复

**Comment by hughex** [comment]
您好，由于后台配置错误，导致一部分港股 BMP 权限用户无法获取香港市场行情。
我们为您特别申请了更高级的港股 LV2 权限和港股期权期货 LV2 权限（有效期到 2021/03/28），现已赠送到您的账户，重启 FutuOpenD 客户端即可。
我们会在有效期内尽快修复此问题，给您造成的不便非常抱歉。
