### ISSUE TITLE
缺少必要的参数: securityFirm

### ISSUE THREAD

**Issue by Timlo512** [FutunnOpen/py-futu-api#84]
試運行
from futu import *
pwd_unlock = 'XXXXX'
trd_ctx = OpenHKTradeContext(host='127.0.0.1', port=11111)
print(trd_ctx.unlock_trade(pwd_unlock))
print(trd_ctx.accinfo_query())
trd_ctx.close()

返回:
(-1, '缺少必要的参数: securityFirm')
(-1, '没有解锁交易，请先解锁交易')

FutuOpenD 5.1.1320
py-futu-api 3.25.0
python 3.7.6

**Comment by hughex** [comment]
请将py-futu-api 也更新到5.1，保持和FutuOpenD版本一致。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutunnOpen/py-futu-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 下午2:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FutunnOpen/py-futu-api] 缺少必要的参数: securityFirm (#84)





 
試運行
 from futu import *
 pwd_unlock = 'XXXXX'
 trd_ctx = OpenHKTradeContext(host='127.0.0.1', port=11111)
 print(trd_ctx.unlock_trade(pwd_unlock))
 print(trd_ctx.accinfo_query())
 trd_ctx.close()
 
返回:
 (-1, '缺少必要的参数: securityFirm')
 (-1, '没有解锁交易，请先解锁交易')
 
FutuOpenD 5.1.1320
 py-futu-api 3.25.0
 python 3.7.6

**Comment by Timlo512** [comment]
Solved
