### ISSUE TITLE
汇率查询 api

### ISSUE THREAD

**Issue by xionghuaidong** [FutunnOpen/py-futu-api#89]
富途牛牛 app 里面可以查看实时汇率，但我没有在 Futu OpenAPI 文档里面找到相关接口，只找到某些接口说不支持外汇的说明。
既然富途牛牛 app 里面可以实时汇率，提供一个 api 应该不难，请添加以方便实时计算人民币市值。
类似：
import futu
quote_ctx = futu.OpenQuoteContext(host='127.0.0.1', port=10001)
with quote_ctx:
    rc, df = quote_ctx.get_market_snapshot('HKDCNY')
df

**Comment by byblehua** [comment]
暂不支持汇率接口
