### ISSUE TITLE
请求历史数据失败

### ISSUE THREAD

**Issue by seflerZ** [FutunnOpen/py-futu-api#9]
返回： NN_ProtoRet_TimeOut

**Comment by FutunnOpen** [comment]
你好，请完整描述问题，或者在用户群（229850364）找管理员解决，谢谢~

**Comment by zhoubinjason** [comment]
ret, data = self.quote_ctx.get_market_snapshot(['US.TSLA'])

总是会返回NN_ProtoRet_TimeOut

FutuOpenD版本信息:1.09.304体验版
启动时间:2019-04-05 12:11:45
FutuOpenD运行中
加载配置文件成功
服务器启动
API监听地址: 0.0.0.0:11111

**Comment by slarkcoder** [comment]
同问，什么时候可以解决？
