### ISSUE TITLE
美股期权链查询 get_option_chain 能不能查询超过30天，弄个60天或者90天的可以吗？

### ISSUE THREAD

**Issue by solarcult** [FutunnOpen/py-futu-api#93]
美股期权链查询 get_option_chain 能不能查询超过30天，弄个60天或者90天的可以吗？

或者可以自定义时间段，30天太少了，而且还有30秒10次的查询限制，限制太多了。

**Comment by FutunnOpen** [comment]
目前限制如此，可以通过get_option_expiration_date遍历

**Comment by xinmans** [comment]
> 目前限制如此，可以通过get_option_expiration_date遍历

有没有sample，如何遍历呀
