### ISSUE TITLE
在arm架构的linux上无法运行FutuOpenD程序

### ISSUE THREAD

**Issue by wangdachui22** [FutunnOpen/py-futu-api#94]
在arm架构的linux上无法运行FutuOpenD程序
# ./FutuOpenD 
/lib64/ld-linux-x86-64.so.2: No such file or directory

**Comment by loadatom** [comment]
FutuOpenD目前不支持arm架构的linux。建议先使用amd64架构的linux。

**Comment by wangdachui22** [comment]
请问有打算支持吗？在什么时候支持？

**Comment by loadatom** [comment]
目前没有计划支持。ARM架构的Linux一般在什么场景下使用呢？我们评估一下
