### ISSUE TITLE
富途证券（香港）MNQ, MES, MYM订阅和交易

### ISSUE THREAD

**Issue by simonfongnt** [FutunnOpen/py-futu-api#95]
在Futu API中如何能订阅[美国指数期货MNQ, MES, MYM](https://www.futuhk.com/about/commissionnew?lang=zh-hk&_gl=1*iklyd4*_ga*Nzc3NzgwNTQ4LjE2MTIzMjI4OTg.*_ga_K1RSSMGBHL*MTYyOTM0MTg2NS41LjEuMTYyOTM0MTg5Ny4w&_ga=2.218883738.2007563781.1629341866-777780548.1612322898&_gac=1.93415023.1629341882.CjwKCAjw3_KIBhA2EiwAaAAlii152LYcmqei81agU4OCFrf3rUt2cOsayhiKwjLMlV-wn7len2DGTBoCXG0QAvD_BwE#us)?
在帐户中, 是否只需要订阅`Nasdaq Basic`就能在API中订阅和交易MNQ, MES, MYM?

如何得到它们的实时报价? 它们在`quote_ctx.subscribe()`的代码是什么? 是否可以从`quote_ctx.get_stock_filter()`得到期货合约代码?

在交易时, 是用
`OpenUSTradeContext(host='127.0.0.1', port=11111, is_encrypt=None, security_firm=SecurityFirm.FUTUSECURITIES)`
还是
`OpenFutureTradeContext(host='127.0.0.1', port=11111, is_encrypt=None, security_firm=SecurityFirm.FUTUSECURITIES)`?

在Futu API中, 如何能用到模拟交易功能?

**Comment by FutunnOpen** [comment]
目前FutuAPI不支持没过期货数据。

**Comment by simonfongnt** [comment]
> 目前FutuAPI不支持没过期货数据。

在帐户中, 若订阅Nasdaq Basic, 只能在API中得到MNQ, MES, MYM的已过期货数据历史数据?

> 期货合约代码暂不支持通过FutuAPI获取

那么它们的期货合约代码是什么?
还是现时不能经API做这3种期货订阅和交易?
